<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap5\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Country $model
*/

$this->title = Yii::t('models', 'Country');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models.plural', 'Country'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud country-view">

    <h1>
        <?= Html::encode($model->name) ?>
        <small><?= 'Country' ?></small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>

                        <?php 
 echo Html::a(
            '<i class="feather icon-edit"></i> ' . 'Edit Country',
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info'])
            ?>
            
                                    <?php 
 echo Html::a(
            '<i class="feather icon-copy"></i> ' . 'Copy Country',
            ['create', 'id' => $model->id, 'Country'=> $model->hasMethod('getCopyParams') ? $model->getCopyParams() : $model->attributes],
            ['class' => 'btn btn-success'])
            ?>
                        
                        <?php 
 echo Html::a(
            '<i class="feather icon-plus"></i> ' . 'New Country',
            ['create'],
            ['class' => 'btn btn-success'])
            ?>
                    </div>

        <div class="pull-right">
            <?= Html::a('<i class="feather icon-list"></i> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\Country'); ?>

    
    <?php 
 echo DetailView::widget([
    'model' => $model,
    'attributes' => [
            'status',
        'name',
        'language',
        'lang_code',
        'country_code',
        'mobile_code',
        'flag',
    ],
    ]);
    ?>

    
    <hr/>

        <?php 
 echo Html::a('<i class="feather icon-trash-2"></i> '
    . 'Delete Country', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]);
    ?>
        <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('Customers'); ?>
<div style='float:right;'>
  <?php
        echo Html::a(
            '<i class="feather icon-list"></i> ' . 'List All Customers',
            ['customer/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<i class="feather icon-plus"></i> ' . 'New Customers',
             ['customer/create', 'Customer' => ['country_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
<div class='clearfix'></div><?php Pjax::begin(['id'=>'pjax-Customers', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Customers ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getCustomers(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-customers',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::class,
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'customer' . '/' . $action;
        $params['Customer'] = ['country_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'customer'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::class,
    'attribute' => 'user_id',
    'value' => function ($model) {
        if ($rel = $model->user) {
            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'name',
        'email:email',
        'mobile_no',
        'referral_code',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::class,
    'attribute' => 'country_id',
    'value' => function ($model) {
        if ($rel = $model->country) {
            return Html::a($rel->name, ['country/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'status',
        'created_at',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('States'); ?>
<div style='float:right;'>
  <?php
        echo Html::a(
            '<i class="feather icon-list"></i> ' . 'List All States',
            ['states/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<i class="feather icon-plus"></i> ' . 'New States',
             ['states/create', 'States' => ['country_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
<div class='clearfix'></div><?php Pjax::begin(['id'=>'pjax-States', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-States ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getStates(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-states',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::class,
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'states' . '/' . $action;
        $params['States'] = ['country_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'states'
],
        'id',
        'name',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::class,
    'attribute' => 'country_id',
    'value' => function ($model) {
        if ($rel = $model->country) {
            return Html::a($rel->name, ['country/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'status',
        'created_at',
        'updated_at',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?php 
        echo Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b>' . \Yii::t('cruds', '# {primaryKey}', ['primaryKey' => Html::encode($model->id)]) . '</b>',
    'content' => $this->blocks['app\models\Country'],
    'active'  => true,
],
[
    'content' => $this->blocks['Customers'],
    'label'   => '<small>' . 'Customers' .' <span class="badge badge-default">'. $model->getCustomers()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['States'],
    'label'   => '<small>' . 'States' .' <span class="badge badge-default">'. $model->getStates()->count() . '</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
