<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%country}}`.
 */
class m240919_095500_create_country_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%country}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string(100)->notNull()->comment('Country name'),
            'language' => $this->string(50)->notNull()->comment('Primary language'),
            'lang_code' => $this->string(5)->notNull()->comment('Language code (e.g., en, es, fr)'),
            'country_code' => $this->string(3)->notNull()->comment('Country code (e.g., USA, CAN, GBR)'),
            'mobile_code' => $this->string(10)->notNull()->comment('Mobile country code (e.g., +1, +44, +91)'),
            'flag' => $this->string(10)->notNull()->comment('Flag emoji or code'),
            'status' => $this->tinyInteger(1)->notNull()->defaultValue(1)->comment('Status: 1=Active, 0=Inactive'),
            'created_at' => $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP'),
            'updated_at' => $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        ]);

        // Add indexes
        $this->createIndex('idx-country-name', '{{%country}}', 'name');
        $this->createIndex('idx-country-lang_code', '{{%country}}', 'lang_code');
        $this->createIndex('idx-country-country_code', '{{%country}}', 'country_code');
        $this->createIndex('idx-country-mobile_code', '{{%country}}', 'mobile_code');
        $this->createIndex('idx-country-status', '{{%country}}', 'status');

        // Insert all country data
        $this->batchInsert('{{%country}}', 
            ['name', 'language', 'lang_code', 'country_code', 'mobile_code', 'flag', 'status'], 
            [
                ['Afghanistan', 'Pashto', 'ps', 'AFG', '+93', '🇦🇫', 1],
                ['Albania', 'Albanian', 'sq', 'ALB', '+355', '🇦🇱', 1],
                ['Algeria', 'Arabic', 'ar', 'DZA', '+213', '🇩🇿', 1],
                ['Andorra', 'Catalan', 'ca', 'AND', '+376', '🇦🇩', 1],
                ['Angola', 'Portuguese', 'pt', 'AGO', '+244', '🇦🇴', 1],
                ['Argentina', 'Spanish', 'es', 'ARG', '+54', '🇦🇷', 1],
                ['Armenia', 'Armenian', 'hy', 'ARM', '+374', '🇦🇲', 1],
                ['Australia', 'English', 'en', 'AUS', '+61', '🇦🇺', 1],
                ['Austria', 'German', 'de', 'AUT', '+43', '🇦🇹', 1],
                ['Azerbaijan', 'Azerbaijani', 'az', 'AZE', '+994', '🇦🇿', 1],
                ['Bahamas', 'English', 'en', 'BHS', '+1242', '🇧🇸', 1],
                ['Bahrain', 'Arabic', 'ar', 'BHR', '+973', '🇧🇭', 1],
                ['Bangladesh', 'Bengali', 'bn', 'BGD', '+880', '🇧🇩', 1],
                ['Barbados', 'English', 'en', 'BRB', '+1246', '🇧🇧', 1],
                ['Belarus', 'Belarusian', 'be', 'BLR', '+375', '🇧🇾', 1],
                ['Belgium', 'Dutch', 'nl', 'BEL', '+32', '🇧🇪', 1],
                ['Belize', 'English', 'en', 'BLZ', '+501', '🇧🇿', 1],
                ['Benin', 'French', 'fr', 'BEN', '+229', '🇧🇯', 1],
                ['Bhutan', 'Dzongkha', 'dz', 'BTN', '+975', '🇧🇹', 1],
                ['Bolivia', 'Spanish', 'es', 'BOL', '+591', '🇧🇴', 1],
                ['Bosnia and Herzegovina', 'Bosnian', 'bs', 'BIH', '+387', '🇧🇦', 1],
                ['Botswana', 'English', 'en', 'BWA', '+267', '🇧🇼', 1],
                ['Brazil', 'Portuguese', 'pt', 'BRA', '+55', '🇧🇷', 1],
                ['Brunei', 'Malay', 'ms', 'BRN', '+673', '🇧🇳', 1],
                ['Bulgaria', 'Bulgarian', 'bg', 'BGR', '+359', '🇧🇬', 1],
                ['Burkina Faso', 'French', 'fr', 'BFA', '+226', '🇧🇫', 1],
                ['Burundi', 'Kirundi', 'rn', 'BDI', '+257', '🇧🇮', 1],
                ['Cambodia', 'Khmer', 'km', 'KHM', '+855', '🇰🇭', 1],
                ['Cameroon', 'French', 'fr', 'CMR', '+237', '🇨🇲', 1],
                ['Canada', 'English', 'en', 'CAN', '+1', '🇨🇦', 1],
                ['Cape Verde', 'Portuguese', 'pt', 'CPV', '+238', '🇨🇻', 1],
                ['Central African Republic', 'French', 'fr', 'CAF', '+236', '🇨🇫', 1],
                ['Chad', 'French', 'fr', 'TCD', '+235', '🇹🇩', 1],
                ['Chile', 'Spanish', 'es', 'CHL', '+56', '🇨🇱', 1],
                ['China', 'Chinese', 'zh', 'CHN', '+86', '🇨🇳', 1],
                ['Colombia', 'Spanish', 'es', 'COL', '+57', '🇨🇴', 1],
                ['Comoros', 'Comorian', 'sw', 'COM', '+269', '🇰🇲', 1],
                ['Congo', 'French', 'fr', 'COG', '+242', '🇨🇬', 1],
                ['Costa Rica', 'Spanish', 'es', 'CRI', '+506', '🇨🇷', 1],
                ['Croatia', 'Croatian', 'hr', 'HRV', '+385', '🇭🇷', 1],
                ['Cuba', 'Spanish', 'es', 'CUB', '+53', '🇨🇺', 1],
                ['Cyprus', 'Greek', 'el', 'CYP', '+357', '🇨🇾', 1],
                ['Czech Republic', 'Czech', 'cs', 'CZE', '+420', '🇨🇿', 1],
                ['Denmark', 'Danish', 'da', 'DNK', '+45', '🇩🇰', 1],
                ['Djibouti', 'French', 'fr', 'DJI', '+253', '🇩🇯', 1],
                ['Dominica', 'English', 'en', 'DMA', '+1767', '🇩🇲', 1],
                ['Dominican Republic', 'Spanish', 'es', 'DOM', '+1809', '🇩🇴', 1],
                ['Ecuador', 'Spanish', 'es', 'ECU', '+593', '🇪🇨', 1],
                ['Egypt', 'Arabic', 'ar', 'EGY', '+20', '🇪🇬', 1],
                ['El Salvador', 'Spanish', 'es', 'SLV', '+503', '🇸🇻', 1],
                ['Equatorial Guinea', 'Spanish', 'es', 'GNQ', '+240', '🇬🇶', 1],
                ['Eritrea', 'Tigrinya', 'ti', 'ERI', '+291', '🇪🇷', 1],
                ['Estonia', 'Estonian', 'et', 'EST', '+372', '🇪🇪', 1],
                ['Ethiopia', 'Amharic', 'am', 'ETH', '+251', '🇪🇹', 1],
                ['Fiji', 'English', 'en', 'FJI', '+679', '🇫🇯', 1],
                ['Finland', 'Finnish', 'fi', 'FIN', '+358', '🇫🇮', 1],
                ['France', 'French', 'fr', 'FRA', '+33', '🇫🇷', 1],
                ['Gabon', 'French', 'fr', 'GAB', '+241', '🇬🇦', 1],
                ['Gambia', 'English', 'en', 'GMB', '+220', '🇬🇲', 1],
                ['Georgia', 'Georgian', 'ka', 'GEO', '+995', '🇬🇪', 1],
                ['Germany', 'German', 'de', 'DEU', '+49', '🇩🇪', 1],
                ['Ghana', 'English', 'en', 'GHA', '+233', '🇬🇭', 1],
                ['Greece', 'Greek', 'el', 'GRC', '+30', '🇬🇷', 1],
                ['Grenada', 'English', 'en', 'GRD', '+1473', '🇬🇩', 1],
                ['Guatemala', 'Spanish', 'es', 'GTM', '+502', '🇬🇹', 1],
                ['Guinea', 'French', 'fr', 'GIN', '+224', '🇬🇳', 1],
                ['Guinea-Bissau', 'Portuguese', 'pt', 'GNB', '+245', '🇬🇼', 1],
                ['Guyana', 'English', 'en', 'GUY', '+592', '🇬🇾', 1],
                ['Haiti', 'French', 'fr', 'HTI', '+509', '🇭🇹', 1],
                ['Honduras', 'Spanish', 'es', 'HND', '+504', '🇭🇳', 1],
                ['Hungary', 'Hungarian', 'hu', 'HUN', '+36', '🇭🇺', 1],
                ['Iceland', 'Icelandic', 'is', 'ISL', '+354', '🇮🇸', 1],
                ['India', 'Hindi', 'hi', 'IND', '+91', '🇮🇳', 1],
                ['Indonesia', 'Indonesian', 'id', 'IDN', '+62', '🇮🇩', 1],
                ['Iran', 'Persian', 'fa', 'IRN', '+98', '🇮🇷', 1],
                ['Iraq', 'Arabic', 'ar', 'IRQ', '+964', '🇮🇶', 1],
                ['Ireland', 'Irish', 'ga', 'IRL', '+353', '🇮🇪', 1],
                ['Israel', 'Hebrew', 'he', 'ISR', '+972', '🇮🇱', 1],
                ['Italy', 'Italian', 'it', 'ITA', '+39', '🇮🇹', 1],
                ['Jamaica', 'English', 'en', 'JAM', '+1876', '🇯🇲', 1],
                ['Japan', 'Japanese', 'ja', 'JPN', '+81', '🇯🇵', 1],
                ['Jordan', 'Arabic', 'ar', 'JOR', '+962', '🇯🇴', 1],
                ['Kazakhstan', 'Kazakh', 'kk', 'KAZ', '+7', '🇰🇿', 1],
                ['Kenya', 'Swahili', 'sw', 'KEN', '+254', '🇰🇪', 1],
                ['Kiribati', 'English', 'en', 'KIR', '+686', '🇰🇮', 1],
                ['Kuwait', 'Arabic', 'ar', 'KWT', '+965', '🇰🇼', 1],
                ['Kyrgyzstan', 'Kyrgyz', 'ky', 'KGZ', '+996', '🇰🇬', 1],
                ['Laos', 'Lao', 'lo', 'LAO', '+856', '🇱🇦', 1],
                ['Latvia', 'Latvian', 'lv', 'LVA', '+371', '🇱🇻', 1],
                ['Lebanon', 'Arabic', 'ar', 'LBN', '+961', '🇱🇧', 1],
                ['Lesotho', 'Sesotho', 'st', 'LSO', '+266', '🇱🇸', 1],
                ['Liberia', 'English', 'en', 'LBR', '+231', '🇱🇷', 1],
                ['Libya', 'Arabic', 'ar', 'LBY', '+218', '🇱🇾', 1],
                ['Liechtenstein', 'German', 'de', 'LIE', '+423', '🇱🇮', 1],
                ['Lithuania', 'Lithuanian', 'lt', 'LTU', '+370', '🇱🇹', 1],
                ['Luxembourg', 'Luxembourgish', 'lb', 'LUX', '+352', '🇱🇺', 1],
                ['Madagascar', 'Malagasy', 'mg', 'MDG', '+261', '🇲🇬', 1],
                ['Malawi', 'English', 'en', 'MWI', '+265', '🇲🇼', 1],
                ['Malaysia', 'Malay', 'ms', 'MYS', '+60', '🇲🇾', 1],
                ['Maldives', 'Maldivian', 'dv', 'MDV', '+960', '🇲🇻', 1],
                ['Mali', 'French', 'fr', 'MLI', '+223', '🇲🇱', 1],
                ['Malta', 'Maltese', 'mt', 'MLT', '+356', '🇲🇹', 1],
                ['Marshall Islands', 'English', 'en', 'MHL', '+692', '🇲🇭', 1],
                ['Mauritania', 'Arabic', 'ar', 'MRT', '+222', '🇲🇷', 1],
                ['Mauritius', 'English', 'en', 'MUS', '+230', '🇲🇺', 1],
                ['Mexico', 'Spanish', 'es', 'MEX', '+52', '🇲🇽', 1],
                ['Micronesia', 'English', 'en', 'FSM', '+691', '🇫🇲', 1],
                ['Moldova', 'Romanian', 'ro', 'MDA', '+373', '🇲🇩', 1],
                ['Monaco', 'French', 'fr', 'MCO', '+377', '🇲🇨', 1],
                ['Mongolia', 'Mongolian', 'mn', 'MNG', '+976', '🇲🇳', 1],
                ['Montenegro', 'Montenegrin', 'sr', 'MNE', '+382', '🇲🇪', 1],
                ['Morocco', 'Arabic', 'ar', 'MAR', '+212', '🇲🇦', 1],
                ['Mozambique', 'Portuguese', 'pt', 'MOZ', '+258', '🇲🇿', 1],
                ['Myanmar', 'Burmese', 'my', 'MMR', '+95', '🇲🇲', 1],
                ['Namibia', 'English', 'en', 'NAM', '+264', '🇳🇦', 1],
                ['Nauru', 'English', 'en', 'NRU', '+674', '🇳🇷', 1],
                ['Nepal', 'Nepali', 'ne', 'NPL', '+977', '🇳🇵', 1],
                ['Netherlands', 'Dutch', 'nl', 'NLD', '+31', '🇳🇱', 1],
                ['New Zealand', 'English', 'en', 'NZL', '+64', '🇳🇿', 1],
                ['Nicaragua', 'Spanish', 'es', 'NIC', '+505', '🇳🇮', 1],
                ['Niger', 'French', 'fr', 'NER', '+227', '🇳🇪', 1],
                ['Nigeria', 'English', 'en', 'NGA', '+234', '🇳🇬', 1],
                ['North Korea', 'Korean', 'ko', 'PRK', '+850', '🇰🇵', 1],
                ['North Macedonia', 'Macedonian', 'mk', 'MKD', '+389', '🇲🇰', 1],
                ['Norway', 'Norwegian', 'no', 'NOR', '+47', '🇳🇴', 1],
                ['Oman', 'Arabic', 'ar', 'OMN', '+968', '🇴🇲', 1],
                ['Pakistan', 'Urdu', 'ur', 'PAK', '+92', '🇵🇰', 1],
                ['Palau', 'English', 'en', 'PLW', '+680', '🇵🇼', 1],
                ['Palestine', 'Arabic', 'ar', 'PSE', '+970', '🇵🇸', 1],
                ['Panama', 'Spanish', 'es', 'PAN', '+507', '🇵🇦', 1],
                ['Papua New Guinea', 'English', 'en', 'PNG', '+675', '🇵🇬', 1],
                ['Paraguay', 'Spanish', 'es', 'PRY', '+595', '🇵🇾', 1],
                ['Peru', 'Spanish', 'es', 'PER', '+51', '🇵🇪', 1],
                ['Philippines', 'Filipino', 'tl', 'PHL', '+63', '🇵🇭', 1],
                ['Poland', 'Polish', 'pl', 'POL', '+48', '🇵🇱', 1],
                ['Portugal', 'Portuguese', 'pt', 'PRT', '+351', '🇵🇹', 1],
                ['Qatar', 'Arabic', 'ar', 'QAT', '+974', '🇶🇦', 1],
                ['Romania', 'Romanian', 'ro', 'ROU', '+40', '🇷🇴', 1],
                ['Russia', 'Russian', 'ru', 'RUS', '+7', '🇷🇺', 1],
                ['Rwanda', 'Kinyarwanda', 'rw', 'RWA', '+250', '🇷🇼', 1],
                ['Saint Kitts and Nevis', 'English', 'en', 'KNA', '+1869', '🇰🇳', 1],
                ['Saint Lucia', 'English', 'en', 'LCA', '+1758', '🇱🇨', 1],
                ['Saint Vincent and the Grenadines', 'English', 'en', 'VCT', '+1784', '🇻🇨', 1],
                ['Samoa', 'Samoan', 'sm', 'WSM', '+685', '🇼🇸', 1],
                ['San Marino', 'Italian', 'it', 'SMR', '+378', '🇸🇲', 1],
                ['Sao Tome and Principe', 'Portuguese', 'pt', 'STP', '+239', '🇸🇹', 1],
                ['Saudi Arabia', 'Arabic', 'ar', 'SAU', '+966', '🇸🇦', 1],
                ['Senegal', 'French', 'fr', 'SEN', '+221', '🇸🇳', 1],
                ['Serbia', 'Serbian', 'sr', 'SRB', '+381', '🇷🇸', 1],
                ['Seychelles', 'English', 'en', 'SYC', '+248', '🇸🇨', 1],
                ['Sierra Leone', 'English', 'en', 'SLE', '+232', '🇸🇱', 1],
                ['Singapore', 'English', 'en', 'SGP', '+65', '🇸🇬', 1],
                ['Slovakia', 'Slovak', 'sk', 'SVK', '+421', '🇸🇰', 1],
                ['Slovenia', 'Slovenian', 'sl', 'SVN', '+386', '🇸🇮', 1],
                ['Solomon Islands', 'English', 'en', 'SLB', '+677', '🇸🇧', 1],
                ['Somalia', 'Somali', 'so', 'SOM', '+252', '🇸🇴', 1],
                ['South Africa', 'English', 'en', 'ZAF', '+27', '🇿🇦', 1],
                ['South Korea', 'Korean', 'ko', 'KOR', '+82', '🇰🇷', 1],
                ['South Sudan', 'English', 'en', 'SSD', '+211', '🇸🇸', 1],
                ['Spain', 'Spanish', 'es', 'ESP', '+34', '🇪🇸', 1],
                ['Sri Lanka', 'Sinhala', 'si', 'LKA', '+94', '🇱🇰', 1],
                ['Sudan', 'Arabic', 'ar', 'SDN', '+249', '🇸🇩', 1],
                ['Suriname', 'Dutch', 'nl', 'SUR', '+597', '🇸🇷', 1],
                ['Sweden', 'Swedish', 'sv', 'SWE', '+46', '🇸🇪', 1],
                ['Switzerland', 'German', 'de', 'CHE', '+41', '🇨🇭', 1],
                ['Syria', 'Arabic', 'ar', 'SYR', '+963', '🇸🇾', 1],
                ['Taiwan', 'Chinese', 'zh', 'TWN', '+886', '🇹🇼', 1],
                ['Tajikistan', 'Tajik', 'tg', 'TJK', '+992', '🇹🇯', 1],
                ['Tanzania', 'Swahili', 'sw', 'TZA', '+255', '🇹🇿', 1],
                ['Thailand', 'Thai', 'th', 'THA', '+66', '🇹🇭', 1],
                ['Timor-Leste', 'Tetum', 'tet', 'TLS', '+670', '🇹🇱', 1],
                ['Togo', 'French', 'fr', 'TGO', '+228', '🇹🇬', 1],
                ['Tonga', 'Tongan', 'to', 'TON', '+676', '🇹🇴', 1],
                ['Trinidad and Tobago', 'English', 'en', 'TTO', '+1868', '🇹🇹', 1],
                ['Tunisia', 'Arabic', 'ar', 'TUN', '+216', '🇹🇳', 1],
                ['Turkey', 'Turkish', 'tr', 'TUR', '+90', '🇹🇷', 1],
                ['Turkmenistan', 'Turkmen', 'tk', 'TKM', '+993', '🇹🇲', 1],
                ['Tuvalu', 'English', 'en', 'TUV', '+688', '🇹🇻', 1],
                ['Uganda', 'English', 'en', 'UGA', '+256', '🇺🇬', 1],
                ['Ukraine', 'Ukrainian', 'uk', 'UKR', '+380', '🇺🇦', 1],
                ['United Arab Emirates', 'Arabic', 'ar', 'ARE', '+971', '🇦🇪', 1],
                ['United Kingdom', 'English', 'en', 'GBR', '+44', '🇬🇧', 1],
                ['United States', 'English', 'en', 'USA', '+1', '🇺🇸', 1],
                ['Uruguay', 'Spanish', 'es', 'URY', '+598', '🇺🇾', 1],
                ['Uzbekistan', 'Uzbek', 'uz', 'UZB', '+998', '🇺🇿', 1],
                ['Vanuatu', 'Bislama', 'bi', 'VUT', '+678', '🇻🇺', 1],
                ['Vatican City', 'Italian', 'it', 'VAT', '+379', '🇻🇦', 1],
                ['Venezuela', 'Spanish', 'es', 'VEN', '+58', '🇻🇪', 1],
                ['Vietnam', 'Vietnamese', 'vi', 'VNM', '+84', '🇻🇳', 1],
                ['Yemen', 'Arabic', 'ar', 'YEM', '+967', '🇾🇪', 1],
                ['Zambia', 'English', 'en', 'ZMB', '+260', '🇿🇲', 1],
                ['Zimbabwe', 'English', 'en', 'ZWE', '+263', '🇿🇼', 1],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%country}}');
    }
}
