<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "income".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property string $date
 * @property integer $type
 * @property integer $level
 * @property string $amount
 * @property integer $status
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Customer $customer
 */
abstract class Income extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'income';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'date', 'type', 'amount'], 'required'],
            [['customer_id', 'type', 'level', 'status', 'created_at', 'updated_at'], 'integer'],
            [['date'], 'safe'],
            [['amount'], 'number'],
            [['meta'], 'string'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Customer::class, 'targetAttribute' => ['customer_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'date' => 'Date',
            'type' => 'Type',
            'level' => 'Level',
            'amount' => 'Amount',
            'status' => 'Status',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\app\models\Customer::class, ['id' => 'customer_id']);
    }
}