<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "level_plan".
 *
 * @property integer $id
 * @property integer $level
 * @property string $rate
 * @property integer $no_of_directs
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class LevelPlan extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'level_plan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
        ];
        
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['status'], 'default', 'value' => 1],
            [['level', 'rate'], 'required'],
            [['level', 'no_of_directs', 'status'], 'integer'],
            [['rate'], 'number', 'min' => 0, 'max' => 100],
            [['level'], 'unique'],
            [['level'], 'integer', 'min' => 1],
            [['no_of_directs'], 'integer', 'min' => 0],
            [['status'], 'in', 'range' => [0, 1]]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'level' => 'Level',
            'rate' => 'Rate (%)',
            'no_of_directs' => 'Number of Directs',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'level' => 'Level number (must be unique)',
            'rate' => 'Commission rate percentage (0-100)',
            'no_of_directs' => 'Required number of direct referrals',
            'status' => 'Active (1) or Inactive (0)',
        ]);
    }

    /**
     * Get status options
     * @return array
     */
    public static function getStatusOptions()
    {
        return [
            0 => 'Inactive',
            1 => 'Active'
        ];
    }

    /**
     * Get status label
     * @return string
     */
    public function getStatusLabel()
    {
        $options = self::getStatusOptions();
        return isset($options[$this->status]) ? $options[$this->status] : 'Unknown';
    }

    /**
     * Get formatted rate
     * @return string
     */
    public function getFormattedRate()
    {
        return number_format($this->rate, 2) . '%';
    }
}