<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "roi_plan".
 *
 * @property integer $id
 * @property string $rate
 * @property integer $frequency
 * @property integer $tenure
 * @property string $release_date
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class RoiPlan extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'roi_plan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['status'], 'default', 'value' => 1],
            [['rate', 'frequency', 'tenure', 'release_date'], 'required'],
            [['rate'], 'number'],
            [['frequency', 'tenure', 'status'], 'integer'],
            [['release_date'], 'safe']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'rate' => 'Rate',
            'frequency' => 'Frequency',
            'tenure' => 'Tenure',
            'release_date' => 'Release Date',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'rate' => 'ROI rate percentage',
            'frequency' => '1=daily, 2=weekly, 3=monthly, 4=yearly',
            'tenure' => 'Number of times (e.g., 2=twice, 3=thrice)',
            'release_date' => 'Release date of the plan',
            'status' => '1=active, 0=inactive',
        ]);
    }

}
