<?php
/**
 * @var yii\web\View $this
 * @var app\models\States $model
 * @var yii\widgets\ActiveForm $form
 */
?>


<!-- attribute status -->
<?php echo $form->field($model, 'status')->textInput() ?>

<!-- attribute name -->
<?php echo $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute country_id -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'country_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Country::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['country_id'])),
    ]
); ?>