<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap5\Tabs;

/**
* @var yii\web\View $this
* @var app\models\States $model
*/

$this->title = Yii::t('models', 'States');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models.plural', 'States'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud states-view">

    <h1>
        <?= Html::encode($model->name) ?>
        <small><?= 'States' ?></small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>

                        <?php 
 echo Html::a(
            '<i class="feather icon-edit"></i> ' . 'Edit States',
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info'])
            ?>
            
                                    <?php 
 echo Html::a(
            '<i class="feather icon-copy"></i> ' . 'Copy States',
            ['create', 'id' => $model->id, 'States'=> $model->hasMethod('getCopyParams') ? $model->getCopyParams() : $model->attributes],
            ['class' => 'btn btn-success'])
            ?>
                        
                        <?php 
 echo Html::a(
            '<i class="feather icon-plus"></i> ' . 'New States',
            ['create'],
            ['class' => 'btn btn-success'])
            ?>
                    </div>

        <div class="pull-right">
            <?= Html::a('<i class="feather icon-list"></i> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\States'); ?>

    
    <?php 
 echo DetailView::widget([
    'model' => $model,
    'attributes' => [
            'status',
        'name',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'country_id',
    'value' => ($model->country ? 
        Html::a('<i class="feather icon-list"></i>', ['country/index']).' '.
        Html::a('<i class="feather icon-arrow-right-circle"></i> '.$model->country->name, ['country/view', 'id' => $model->country->id,]).' '.
        Html::a('<i class="feather icon-link"></i>', ['create', 'States'=>['country_id' => $model->country_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
    ],
    ]);
    ?>

    
    <hr/>

        <?php 
 echo Html::a('<i class="feather icon-trash-2"></i> '
    . 'Delete States', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]);
    ?>
        <?php $this->endBlock(); ?>


    
    <?php 
        echo Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b>' . \Yii::t('cruds', '# {primaryKey}', ['primaryKey' => Html::encode($model->id)]) . '</b>',
    'content' => $this->blocks['app\models\States'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
